### PR TITLE
Chip Component

### PR DESCRIPTION
**Pull request by henon**
Work in Progress
- [x] Basic: IsClickable==false => Chip does not hover and shows no ripple
- [x] Clickable: IsClickable==true => makes the chip interactive and shows a ripple on click
- [x] Chip.IsDeletable makes EndIcon clickable and displays a remove Icon when no end-icon is set. 
- [x] Deletable: When clicked, set IsDeleted and hide the chip
- [x] Avatar: Letter, Image
- [x] Size: Small 
- [x] Outlined

Work in Progress, not ready for merging yet.

### CODE REVIEW

**Comment by henon** [comment]
yeah, I am getting the hang of it. 

image

**Comment by henon** [comment]
image

**Comment by henon** [comment]
@skclusive: I think you can review this. I think I am pretty much done.

image

**Comment by skclusive** [comment]
wow. great stuff. merging it.

**Comment by skclusive** [comment]
created documentation issue for Chip https://github.com/skclusive/Skclusive.Material.Docs/issues/14. we can document later too.
 but doing documentation with demo would help us identify bugs or missing functionalities.

**Pull request merged**
